services:
    Sumpfpony\EntityHistoryBundle\Registry\Catalogue: ~
    
    _defaults:
        autowire: true
        autoconfigure: true

    # explicitly configure the service
    Sumpfpony\EntityHistoryBundle\Controller\HistoryController:
        public: false
        calls:
            - method: setStoreAdapter
              arguments:
                  - '@Sumpfpony\EntityHistoryBundle\StoreAdapter\StoreAdapterInterface'


    Sumpfpony\EntityHistoryBundle\Listeners\EntityHistoryListener:
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    

    Sumpfpony\EntityHistoryBundle\StoreAdapter\MonologStoreAdapter: ~
    Sumpfpony\EntityHistoryBundle\StoreAdapter\ElasticSearchAdapter: ~
    Sumpfpony\EntityHistoryBundle\StoreAdapter\DoctrineAdapter:
      calls:
            - {method: setEntityManager, arguments: ["@doctrine.orm.entity_manager"]}

